version: '3'

services:
  mysql:
    container_name: phonebook_mysql
    build:
      context: mysql
      args:
        - MYCONF=my.cnf
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_USER: phonebook
      MYSQL_PASSWORD: phonebook
      MYSQL_DATABASE: phonebook
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 33377:3306

  nginx:
    container_name: phonebook_nginx
    image: nginx:stable-alpine
    volumes:
       - ./app/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
       - ./data/app:/app
    links:
      - app
    depends_on:
      - app
    ports:
      - 30999:80

  app:
    container_name: phonebook_app
    build:
        context: ../
        dockerfile: docker/data/Dockerfile
    volumes:
        - ./app/php/custom.php.ini:/usr/local/etc/php/conf.d/custom.ini
        - ./data/app:/app
    expose:
      - 9000
    depends_on:
      - mysql


